from database.supabase_client import get_supabase_client

def save_diagnosis(user_id: str, report_id: str, question: str, answer: str) -> tuple[dict, int]:
    """
    Saves a diagnosis generated by the AI to the database.
    """
    try:
        supabase = get_supabase_client()
        result = supabase.table("diagnoses").insert({
            "user_id": user_id,
            "report_id": report_id,
            "question": question,
            "answer": answer
        }).execute()
        
        if not result.data or len(result.data) == 0:
            return {"success": False, "message": "Failed to save diagnosis."}, 500
            
        return {"success": True, "data": result.data[0]}, 201
    except Exception as e:
        return {"success": False, "message": f"Database error: {str(e)}"}, 500


def get_diagnoses_by_patient_name(patient_name: str) -> tuple[dict, int]:
    """
    Searches for a patient by their full name and returns their diagnosis history.
    """
    try:
        supabase = get_supabase_client()
        
        # 1. Find user by name
        user_result = supabase.table("users") \
            .select("id, full_name, email") \
            .ilike("full_name", f"%{patient_name}%") \
            .eq("role", "patient") \
            .execute()
            
        if not user_result.data or len(user_result.data) == 0:
            return {"success": False, "message": "No patient found with that name."}, 404
            
        # For simplicity, if multiple match, we take the first one or we can return all.
        # Let's return all diagnoses for the matched users.
        user_ids = [user["id"] for user in user_result.data]
        user_map = {str(user["id"]): user["full_name"] for user in user_result.data}
        
        # 2. Get diagnoses for those users
        diag_result = supabase.table("diagnoses") \
            .select("*, reports(report_name)") \
            .in_("user_id", user_ids) \
            .order("created_at", desc=True) \
            .execute()
            
        diagnoses = []
        if diag_result.data:
            for d in diag_result.data:
                diagnoses.append({
                    "id": str(d["id"]),
                    "patient_name": user_map.get(str(d["user_id"]), "Unknown"),
                    "report_name": d.get("reports", {}).get("report_name", "Unknown Report") if d.get("reports") else "Unknown Report",
                    "question": d["question"],
                    "answer": d["answer"],
                    "created_at": d.get("created_at")
                })
                
        return {"success": True, "data": diagnoses}, 200
        
    except Exception as e:
        return {"success": False, "message": f"Database error: {str(e)}"}, 500
